[package]
symbol = 'ğŸ“¦'

[git_status]
windows_starship = '/mnt/c/Users/matsixfive/.cargo/bin/starship.exe'

[directory]
read_only = ' ï€£'
read_only_style = 'bold #f9c23c'

[zig]
symbol = 'âš¡ï¸'
version_format = 'v${major}.${minor}.${patch}'

[bun]
symbol = 'ğŸ§„'
style = 'bold yellow'

[golang]
symbol = 'î˜¦ '

[rust]
symbol = 'ğŸ¦€'

[container]
disabled = true
