[package]
# symbol = 'î¬© '
symbol = 'ó°—'

[git_status]
windows_starship = '/mnt/c/Users/maffe/.cargo/bin/starship.exe'

[directory]
read_only = ' ï€£'
read_only_style = 'bold #f9c23c'

[zig]
symbol = 'âš¡ï¸ '
version_format = 'v${major}.${minor}.${patch}'

[bun]
symbol = 'ğŸ§„ '
style = 'bold yellow'

[golang]
symbol = 'î˜§ '

[rust]
symbol = 'îš‹ '

[java]
symbol = 'î¶¯ '
style = 'bold #f89917'

[gradle]
symbol = 'î™  '

[ruby]
detect_variables = []

[container]
disabled = true
